ad";Hu.aa="//www.google.com/favicon.ico?";Hu.X="//pagead2.googlesyndication.com/favicon.ico?";Hu.Ba=function(a){var c=a.uc(),d={ba:"g_img_dt",url:Hu.aa+c},c={ba:"a_img_dt",url:Hu.X+c};return 0==a.b%2?[d,c]:[c,d]};var Iu=function(){};Iu.id="a2s";Iu.A=".unicast-stb.metric.gstatic.com";Iu.o=".stbcast-stb.metric.gstatic.com";Iu.B={ba:"un_img_dt",ga:Iu.A};Iu.w={ba:"sa_img_dt",ga:Iu.o};Iu.b="/v6exp3/6.gif";Iu.Ba=function(a){return Eu(a,Iu.B,Iu.w,Iu.b)};var Ju=function(){};Ju.id="as";Ju.A=".unicast.metric.gstatic.com";Ju.o=".stbcast.metric.gstatic.com";Ju.B={ba:"un_img_dt",ga:Ju.A};Ju.w={ba:"sa_img_dt",ga:Ju.o};Ju.b="/v6exp3/6.gif";Ju.Ba=function(a){return Eu(a,Ju.B,Ju.w,Ju.b)};var Ku=function(){};Ku.id="au";Ku.A=".unicast-edge.metric.gstatic.com";Ku.o=".anycast-edge.metric.gstatic.com";Ku.B={ba:"un_img_dt",ga:Ku.A};Ku.w={ba:"ua_img_dt",ga:Ku.o};Ku.b="/v6exp3/6.gif";Ku.Ba=function(a){return Eu(a,Ku.B,Ku.w,Ku.b)};var Lu=function(){};Lu.id="ds";Lu.la="-dnssec-nd.gexperiments1.com";Lu.U="-dnssec-vd.gexperiments2.com";Lu.ma={ba:"nd_img_dt",ga:Lu.la};Lu.R={ba:"vd_img_dt",ga:Lu.U};Lu.Ba=function(a){return Eu(a,Lu.ma,Lu.R,"/dnssec/1.gif")};var Mu=function(){};Mu.id="dv";Mu.U="-bogus-dnssec-vd.gexperiments2.com";Mu.W="-bogus-dnssec-bd.gexperiments3.com";Mu.R={ba:"vd_img_dt",ga:Mu.U};Mu.Y={ba:"bd_img_dt",ga:Mu.W};Mu.Ba=function(a){return Eu(a,Mu.R,Mu.Y,"/dnssec/1.gif")};var Nu=function(){};Nu.id="3";Nu.ra="-v6exp3.v4.metric.gstatic.com";Nu.Ma="-v6exp3.ds.metric.gstatic.com";Nu.b="/v6exp3/6.gif";Nu.Ya={ba:"v4_img_dt",ga:Nu.ra};Nu.$={ba:"ds_img_dt",ga:Nu.Ma};Nu.Ba=function(a){return Eu(a,Nu.Ya,Nu.$,Nu.b)};var Ou=function(){};Ou.id="dz";Ou.V="-v6exp3-ds.metric.ipv6test.net";Ou.Z="-v6exp3-ds.metric.ipv6test.com";Ou.b="/v6exp3/6.gif";Ou.ca={ba:"4z_img_dt",ga:Ou.V};Ou.da={ba:"dz_img_dt",ga:Ou.Z};Ou.Ba=function(a){return Eu(a,Ou.ca,Ou.da,Ou.b)};var Pu=function(){};Pu.id="dzc";Pu.Ga="//dzc"+Ou.V+"/v6exp3/6.gif?";Pu.ha="//dzc"+Ou.Z+"/v6exp3/6.gif?";Pu.Ba=function(a){var c=a.uc(),d={ba:"4z_img_dt",url:Pu.Ga+c},c={ba:"dz_img_dt",url:Pu.ha+c};return 0==a.b%2?[c,d]:[d,c]};
var Qu=function(){};Qu.id="stb_stb_short";Qu.H=".stbcast3.metric.gstatic.com";Qu.K=".stbcast4.metric.gstatic.com";Qu.ia={ba:"sa3_img_dt",ga:Qu.H};Qu.M={ba:"sa4_img_dt",ga:Qu.K};Qu.b="/v6exp3/6.gif";Qu.Ba=function(a){return Eu(a,Qu.ia,Qu.M,Qu.b)};var Ru=function(){};Ru.id="stb_stb_long";Ru.H=".stbcast3-stb.metric.gstatic.com";Ru.K=".stbcast4-stb.metric.gstatic.com";Ru.ia={ba:"sa3_img_dt",ga:Ru.H};Ru.M={ba:"sa4_img_dt",ga:Ru.K};Ru.b="/v6exp3/6.gif";Ru.Ba=function(a){return Eu(a,Ru.ia,Ru.M,Ru.b)};
var Su=function(){};Su.id="stb_any_short";Su.F=".stbcast2.metric.gstatic.com";Su.o=".anycast.metric.gstatic.com";Su.G={ba:"sa2_img_dt",ga:Su.F};Su.w={ba:"ua_img_dt",ga:Su.o};Su.b="/v6exp3/6.gif";Su.Ba=function(a){return Eu(a,Su.G,Su.w,Su.b)};var Tu=function(){};Tu.id="stb_any_long";Tu.F=".stbcast2-stb.metric.gstatic.com";Tu.o=".anycast-stb.metric.gstatic.com";Tu.G={ba:"sa2_img_dt",ga:Tu.F};Tu.w={ba:"ua_img_dt",ga:Tu.o};Tu.b="/v6exp3/6.gif";Tu.Ba=function(a){return Eu(a,Tu.G,Tu.w,Tu.b)};var Uu=function(){};Uu.id="uni_uni_short";Uu.sa="-unicast3.metric.gstatic.com";Uu.Ea="-unicast4.metric.gstatic.com";Uu.Da={ba:"un3_img_dt",ga:Uu.sa};Uu.Fa={ba:"un4_img_dt",ga:Uu.Ea};Uu.b="/v6exp3/6.gif";Uu.Ba=function(a){return Eu(a,Uu.Da,Uu.Fa,Uu.b)};
var Vu=function(){};Vu.id="uni_any_short";Vu.Ta=".unicast2.metric.gstatic.com";Vu.C=".anycast2.metric.gstatic.com";Vu.O={ba:"un2_img_dt",ga:Vu.Ta};Vu.D={ba:"ua2_img_dt",ga:Vu.C};Vu.b="/v6exp3/6.gif";Vu.Ba=function(a){return Eu(a,Vu.O,Vu.D,Vu.b)};var Wu=function(){};Wu.id="uni_any_long";Wu.Ta=".unicast2-stb.metric.gstatic.com";Wu.C=".anycast2-stb.metric.gstatic.com";Wu.O={ba:"un2_img_dt",ga:Wu.Ta};Wu.D={ba:"ua2_img_dt",ga:Wu.C};Wu.b="/v6exp3/6.gif";Wu.Ba=function(a){return Eu(a,Wu.O,Wu.D,Wu.b)};
var Xu=[new Fu(.1,!0,Hu),new Fu(1,!0,Ju),new Fu(1,!0,Iu),new Fu(10,!1,Ku),new Fu(1,!0,Lu),new Fu(1,!0,Mu),new Fu(2,!0,Pu),new Fu(4,!0,Ou),new Fu(1,!0,Qu),new Fu(1,!0,Ru),new Fu(1,!0,Su),new Fu(1,!0,Tu),new Fu(1,!0,Uu),new Fu(1,!0,Vu),new Fu(1,!0,Wu),new Fu(72.9,!0,Nu)],Yu=function(a,c,d){this.o=String(a);"p"!=this.o.charAt(0)&&(this.o="p"+this.o);this.A=c;this.w=d;c=Math.random();this.b=Math.floor(9E5*c);this.b+=1E5;a="https:"==window.document.location.protocol;c*=100;d=Xu[Xu.length-1].Hb;var e,f=
0;for(e=0;e<Xu.length&&!(f+=Xu[e].Th,f>=c);e++);e<Xu.length&&(!a||Xu[e].hh)&&(d=Xu[e].Hb);this.Hb=d};Yu.prototype.uc=function(){return["ipv6exp=",this.Hb.id,"&p=",this.o,"&rnd=",this.A,"&hmac=",this.w,"&nonce=",this.b].join("")};
var Zu=function(a){for(var c=a.Hb.Ba(a),d=0;d<c.length;d++){var e=new Gu(c[d].url,c[d].ba);e.b();c[d]=e}(0,window.setTimeout)(function(){var d;d=["/gen_204?ipv6exp="+a.Hb.id,"sentinel=1"];for(var e={sh:[]},h=0;h<c.length;h++)d.push(c[h].uc()),e[c[h].cf()]=c[h].li(),e.sh.push(c[h].cf());d=Du([[a.o,a.A,a.w,a.b].join("-"),"s1"],"-v6exp3-v4.metric.gstatic.com",d);(new window.Image(0,0)).src=d},3E4)},$u=function(a,c,d){var e=new Yu(a,c,d);(0,window.setTimeout)(function(){Zu(e)},1E4)};
var av=function(){var a=Cu()||new Bu;this.A=_.td();this.w=_.M(_.F(a,1));this.o=_.M(_.F(a,2));this.b=_.M(_.F(a,3))};_.S(function(){if(Cu()){var a=new av;if(a.w&&a.o&&a.b)try{var c=[a.w,a.o,a.b,"if-v6exp3-v4.metric.gstatic.com"].join("-")||window.location.hostname,d,e=c.indexOf(".metric.");(d=-1<e?c.substring(0,e).split("-"):c.split("."))&&3<=d.length&&$u(d[0],d[1],d[2])}catch(f){a.A.log(f)}}});

}catch(e){_._DumpException(e)}
/* _Module_:dp */
try{
var cz=function(a){_.E(this,a,0,-1,null)};_.y(cz,_.D);
var dz=function(a,c){c=c||Math.random;for(var d=a.length-1;0<d;d--){var e=Math.floor(c()*(d+1)),f=a[d];a[d]=a[e];a[e]=f}},ez=function(a){for(var c=[],d=0;d<arguments.length;d++){var e=arguments[d];if(_.na(e))for(var f=0;f<e.length;f+=8192)for(var g=ez.apply(null,_.$a(e,f,f+8192)),h=0;h<g.length;h++)c.push(g[h]);else c.push(e)}return c},fz=function(a){a=["https://pagead2.googlesyndication.com/pagead/gen_204?id=drsl&drsl=",a].join("");(new window.Image(0,0)).src=a},gz=function(a){for(var c=[],d=0;d< a.length;d++)a[d]&&c.push(a[d]);return c.join(";")},hz=function(a,c){c=c?c.toString():"";return a?[a,c].join(":"):""};
var iz=function(a){this.o=a};var X=function(a){this.o=a||dz;this.b=[]};_.la(X);var Y=function(a,c){a.b.push(c)},jz=function(){var a=X.N();a.o(a.b);var c=_.$a(a.b,0,2);(0,_.Pa)(c,function(a){try{a.A()}catch(e){try{fz(gz([hz((35).toString(),a.o)]))}catch(f){}}});(0,window.setTimeout)(function(){var a=(0,_.Sa)(c,function(a){return a.B()});fz(gz(a))},1E4)};
var Z=function(a,c){this.b="";this.C=c;this.hasOwnProperty("logger");this.o=a.toString()};_.y(Z,iz);Z.prototype.B=function(){return hz(this.o,this.b.toString())};Z.prototype.A=function(){var a=this.C();_.n(a)&&(this.b=a)};var kz=function(a){return(0,_.u)(function(a){this.b=a},a)};
Y(X.N(),new Z(25,function(a){a=a||window.navigator;return!!a&&"cookieEnabled"in a&&a.cookieEnabled}));Y(X.N(),new Z(30,function(a){a=a||window.document.body;return"borderRadius"in a.style?"border-radius":"WebkitBorderRadius"in a.style?"-webkit-border-radius":"MozBorderRadius"in a.style?"-moz-border-radius":""}));Y(X.N(),new Z(34,function(a){return"openDatabase"in(a||window)}));Y(X.N(),new Z(31,function(a){return"applicationCache"in(a||window)}));Y(X.N(),new Z(33,function(a){return"Storage"in(a||window)}));Y(X.N(),new Z(32,function(a){return"postMessage"in(a||window)}));
var lz=function(a,c,d,e){this.w=!1;this.b=e||function(){};var f=_.n(d)?d:"//www.gstatic.com/drasil/";this.C=(0,_.Sa)(c,function(a){return[f,a].join("")});this.hasOwnProperty("logger");this.o=a.toString()};_.y(lz,iz);lz.prototype.B=function(){return hz(this.o,this.w.toString())};lz.prototype.A=function(){(0,_.Pa)(this.C,function(a){var c=_.P("IMG");c.onload=(0,_.u)(this.handleEvent,this,!0);c.onerror=(0,_.u)(this.handleEvent,this,!1);c.src=a},this)};
lz.prototype.handleEvent=function(a){this.w=this.w||a;this.b();return!1};Y(X.N(),new lz(11,["1x1.gif"]));Y(X.N(),new lz(12,["1x1.jpg"]));Y(X.N(),new lz(13,["1x1.png"]));
Y(X.N(),new lz(14,["data:image/gif;base64,R0lGODdhAQABAIAAAP///////ywAAAAAAQABAAACAkQBADs=","data:image/jpg;base64,/9j/4AAQSkZJRgABAQEASABIAAD//gATQ3JlYXRlZCB3aXRoIEdJTVD/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCAABAAEDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAj/xAAUEAEAAAAAAAAAAAAAAAAAAAAA/8QAFAEBAAAAAAAAAAAAAAAAAAAAAP/EABQRAQAAAAAAAAAAAAAAAAAAAAD/2gAMAwEAAhEDEQA/ALLAB//Z","data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAIAAACQd1PeAAAAAXNSR0IArs4c6QAAAAlwSFlzAAALEwAACxMBAJqcGAAAAAd0SU1FB90KDhEJIUhUqJMAAAAZdEVYdENvbW1lbnQAQ3JlYXRlZCB3aXRoIEdJTVBXgQ4XAAAADElEQVQI12P4//8/AAX+Av7czFnnAAAAAElFTkSuQmCC"], ""));
Y(X.N(),new Z(23,function(a,c){c=c||window;var d=a||kz(this);"setTimeout"in c&&c.setTimeout(function(){d(!0)},0);return!1}));Y(X.N(),new Z(22,function(a,c){var d=c||window,e=a||kz(this);if("setInterval"in d)var f=d.setInterval(function(){d.clearInterval(f);e(!0)},0);return!1}));Y(X.N(),new Z(18,function(a){a=a||window;return!!("alert"in a)&&!!("confirm"in a)}));Y(X.N(),new Z(19,function(a){return"forms"in(a||window.document)}));Y(X.N(),new Z(21,function(a){return"location"in(a||window.document)})); Y(X.N(),new Z(20,function(a){return"getElementById"in(a||window.document)}));Y(X.N(),new Z(17,function(a){a=a||_.P("DIV");var c=a.outerHTML;"style"in a&&(a.style.backgroundColor="red");return c!=a.outerHTML}));
var mz=function(a,c,d){this.w=d||_.p("navigator.plugins")||[];this.hasOwnProperty("logger");Z.call(this,a,c)};_.y(mz,Z);var nz=function(a,c){a=_.Sa(_.Za(a.w),_.Za);c=(0,_.Ra)(ez(a),c);return(0,_.Sa)(c,function(a){return a.enabledPlugin})},oz=function(a,c){return nz(a,function(a){return _.Xa(a.suffixes.split(","),c)})};Y(X.N(),new mz(16,function(){return 0<oz(this,"pdf").length}));Y(X.N(),new mz(15,function(){var a=/Shockwave Flash \d/,c=oz(this,"swf");return 0<(0,_.Ra)(c,function(c){return a.test(c.description)}).length}));
var pz=function(){var a=_.p("window.top.outerHeight")||0,c=_.p("window.devicePixelRatio")||1,d=_.p("screen.height")||0;return d*(a*c>d?c:1)};Y(X.N(),new Z(1,pz));var qz=function(){var a=_.p("window.top.outerWidth")||0,c=_.p("window.devicePixelRatio")||1,d=_.p("screen.width")||0;return d*(a*c>d?c:1)};Y(X.N(),new Z(2,qz));Y(X.N(),new Z(26,function(){return _.p("screen.height")||0}));Y(X.N(),new Z(27,function(){return _.p("screen.width")||0}));
Y(X.N(),new Z(3,function(){var a=rz(),c=pz();return 1==a?0:c/a*25.4}));Y(X.N(),new Z(4,function(){var a=rz(),c=qz();return 1==a?0:c/a*25.4}));Y(X.N(),new Z(28,function(){return _.p("window.devicePixelRatio")||1}));var rz=function(){var a;a:{a=1;var c=1E3;do{var d=Math.floor((c-a)/2+a),e=window.matchMedia("(max-resolution:"+d.toString()+"dpi)").matches,f=window.matchMedia("(min-resolution:"+d.toString()+"dpi)").matches;if(f&&e){a=d;break a}f?a=d+1:c=d-1}while(c>=a);a=null}return a||1};
Y(X.N(),new Z(29,rz));Y(X.N(),new Z(5,function(){return _.p("window.top.outerHeight")||0}));Y(X.N(),new Z(6,function(){return _.p("window.top.outerWidth")||0}));Y(X.N(),new Z(7,function(){return Math.pow(2,_.p("screen.colorDepth")||0)}));Y(X.N(),new Z(24,function(){return"ontouchstart"in window||"onmsgesturechange"in window}));
var tz=function(a,c,d){this.hasOwnProperty("logger");this.D=c;try{this.w=d||window.document.createElement("video")}catch(e){}Z.call(this,a,sz)};_.y(tz,Z);var sz=function(){return""!=(this.w&&this.w.canPlayType||function(){return""}).call(this.w,this.D).replace(/^no$/,"")};Y(X.N(),new tz(8,'video/mp4; codecs="avc1.42E01E, mp4a.40.2"'));Y(X.N(),new tz(9,'video/ogg; codecs="theora"'));Y(X.N(),new tz(10,'video/webm; codecs="vp8, vorbis"'));
_.x("drasil.iframe.run",function(){jz()});_.S(function(){var a=_.K.N().ea;_.J(a,cz,23)&&jz()});
}catch(e){_._DumpException(e)}
/* _Module_:cpd */
try{
var io=function(a,c){_.Ci.call(this,a,c);this.o=_.T("gb_Ne",this.b);this.B=_.bd("el")};_.y(io,_.Ci);io.prototype.D=function(){_.Xh(this.o,_.Fb);this.B.Va()};io.prototype.C=function(a){this.o.appendChild(a);this.B.Va()};_.S(function(){var a=_.T("gb_ef");if(a){var c=_.td(),a=new io(a,c);_.x("gbar.sncw",(0,_.u)(a.D,a));_.x("gbar.snaw",(0,_.u)(a.C,a))}});
}catch(e){_._DumpException(e)}
/* _GlobalSuffix_ */
})(this.gbar_);
// Google Inc.
ÿAóEo˙Ù   ßÎA¬ˇ     
å
GET
accept*/*v

user-agenthMozilla/5.0 (X11; Linux armv7l) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.84 Safari/537.36“» "
age77489"0
alt-svc%quic=":443"; ma=2592000; v="37,36,35"")
cache-controlpublic, max-age=31536000"
content-encodinggzip"
content-length44687".
content-typetext/javascript; charset=UTF-8"%
dateTue, 21 Mar 2017 11:02:52 GMT"(
expiresWed, 21 Mar 2018 11:02:52 GMT".
last-modifiedThu, 16 Mar 2017 02:39:38 GMT"
serversffe"
status200"
varyAccept-Encoding, Origin"!
x-content-type-optionsnosniff"!
x-xss-protection1; mode=block*Íhttps://www.gstatic.com/og/_/js/k=og.og.en_US.pIu6HmSxT9w.O/rt=j/m=ld,gl,is,id,nb,nw,sb,sd,p,vd,awd,st,lod,eld,ip,dp,cpd/exm=bt,base,bn,bu,cp,el,lo,sbi,ni,sf,up,dd,aw,iw,if,gi,vi,pi,eq,uc/d=1/ed=1/rs=AA2YrTuNXpKeqlz64GNaVbOQIQEenrGkfw0á¬•»æº™áÓ…¸ææ™Sr\#¯¶∂otz=¸çµW◊nkNJ®ﬂcD1FVßÑÈxÿAóEo˙Ù   ÂÈJm                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 